#!/usr/bin/env node
// triage-report — point it at a folder of test reports (JUnit XML and/or JSON),
// get a Markdown triage you can post on a merge/pull request.
//
//   node examples/triage-report.mjs <reportsDir>
//   node examples/triage-report.mjs <reportsDir> | gh pr comment <n> --body-file -
//
// It is a THIN runner over the shipped capability: the adapters normalize each
// report into observations, and the evaluator returns the judgment. The only
// glue here is (1) reading a directory and (2) folding the same test across
// several report files into cross-run history — a preview of the run-level
// aggregator that will become a first-class capability method.
//
// NOTE: JUnit shows only a test's final outcome (no per-run retries), so
// within-run flakiness comes from cross-run history. For richer signal, emit
// Playwright's JSON reporter (results[] carries each retry attempt).
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, extname } from "node:path";
import { parseTestReport } from "../dist/capabilities/flaky-test-triage/adapters.js";
import { triageFlakyTest } from "../dist/capabilities/flaky-test-triage/evaluator.js";

const dir = process.argv[2];
if (!dir || !statSync(dir).isDirectory()) {
  console.error("Usage: node examples/triage-report.mjs <reportsDir>");
  process.exit(2);
}

// 1. Read every report file and normalize to observations (auto-detected format).
const files = readdirSync(dir).filter((f) => [".xml", ".json"].includes(extname(f)));
const runs = files.map((f) => parseTestReport(readFileSync(join(dir, f), "utf8")));

// 2. Fold the same test across runs into cross-run history.
const byTest = new Map();
for (const obs of runs.flat()) {
  const cur = byTest.get(obs.testId) ?? { obs, runs: 0, failures: 0, msgs: new Set() };
  cur.runs += 1;
  const failed = obs.attempts.some((a) => a.status === "failed" || a.status === "timedOut");
  if (failed) {
    cur.failures += 1;
    cur.obs = obs;
    obs.attempts.forEach((a) => a.errorMessage && cur.msgs.add(a.errorMessage));
  }
  byTest.set(obs.testId, cur);
}

// 3. Triage every test that failed at least once.
const judged = [];
for (const [, c] of byTest) {
  if (c.failures === 0) continue;
  judged.push(
    triageFlakyTest({
      ...c.obs,
      history: { runs: c.runs, failures: c.failures, distinctErrorMessages: Math.max(c.msgs.size, 1) },
    }),
  );
}

// 4. Fold per-test judgments into one gate decision (preview of the aggregator).
const has = (cls) => judged.some((j) => j.classification === cls);
const gate = judged.length === 0
  ? { label: "✅ VALIDATED", note: "No failing tests in the reports." }
  : has("likely_real_regression")
    ? { label: "⛔ NOT VALIDATED — real regression", note: "A deterministic product failure is present. Do not merge; do not quarantine." }
    : has("test_or_config_error")
      ? { label: "🔧 NEEDS FIX — broken test/config", note: "Failures are in the test setup, not the product. Fix the test/config, then re-run." }
      : { label: "⚠️ VALIDATED WITH FLAKES", note: "Failures look flaky. Safe to merge, but quarantine + follow up on the flakes." };

// 5. Render Markdown.
const total = byTest.size;
const rows = judged.map((j) => {
  const pct = Math.round(j.confidence * 100);
  const q = j.quarantineForbidden ? "⛔ forbidden" : j.quarantineRecommended ? "recommended" : "—";
  return `| \`${j.testId.slice(0, 70)}\` | ${j.classification} | ${pct}% | ${q} |`;
});

const out = [
  "## 🧪 Flaky-Test Triage",
  "",
  `**Gate:** ${gate.label}`,
  `> ${gate.note}`,
  "",
  `Tests seen: **${total}** · failing: **${judged.length}** · reports: ${files.length}`,
  "",
  ...(judged.length
    ? [
        "| Test | Classification | Confidence | Quarantine |",
        "|---|---|---|---|",
        ...rows,
        "",
        "### What to do",
        ...judged.flatMap((j) => [
          `- **${j.testId.slice(0, 70)}** — ${j.recommendedActions[0]?.action ?? ""}`,
        ]),
      ]
    : []),
  "",
  "_Generated by qa-mcp-server · flaky-test-triage_",
].join("\n");

console.log(out);
